# Generated by Django 2.0.9 on 2018-11-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_remove_question_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
    ]
